from _typeshed import Incomplete

import usb._objfinalizer as _objfinalizer


class IBackend(_objfinalizer.AutoFinalizedObject):
    def enumerate_devices(self) -> Never: ...

    def get_parent(self, dev: Incomplete) -> Never: ...

    def get_device_descriptor(self, dev: Incomplete) -> Never: ...

    def get_configuration_descriptor(self, dev: Incomplete, config: Incomplete) -> Never: ...

    def get_interface_descriptor(self, dev: Incomplete, intf: Incomplete, alt: Incomplete, config: Incomplete) -> Never: ...

    def get_endpoint_descriptor(self, dev: Incomplete, ep: Incomplete, intf: Incomplete, alt: Incomplete, config: Incomplete) -> Never: ...

    def open_device(self, dev: Incomplete) -> Never: ...

    def close_device(self, dev_handle: Incomplete) -> Never: ...

    def set_configuration(self, dev_handle: Incomplete, config_value: Incomplete) -> Never: ...

    def get_configuration(self, dev_handle: Incomplete) -> Never: ...

    def set_interface_altsetting(self, dev_handle: Incomplete, intf: Incomplete, altsetting: Incomplete) -> Never: ...

    def claim_interface(self, dev_handle: Incomplete, intf: Incomplete) -> Never: ...

    def release_interface(self, dev_handle: Incomplete, intf: Incomplete) -> Never: ...

    def bulk_write(self, dev_handle: Incomplete, ep: Incomplete, intf: Incomplete, data: Incomplete, timeout: Incomplete) -> Never: ...

    def bulk_read(self, dev_handle: Incomplete, ep: Incomplete, intf: Incomplete, buff: Incomplete, timeout: Incomplete) -> Never: ...

    def intr_write(self, dev_handle: Incomplete, ep: Incomplete, intf: Incomplete, data: Incomplete, timeout: Incomplete) -> Never: ...

    def intr_read(self, dev_handle: Incomplete, ep: Incomplete, intf: Incomplete, size: Incomplete, timeout: Incomplete) -> Never: ...

    def iso_write(self, dev_handle: Incomplete, ep: Incomplete, intf: Incomplete, data: Incomplete, timeout: Incomplete) -> Never: ...

    def iso_read(self, dev_handle: Incomplete, ep: Incomplete, intf: Incomplete, size: Incomplete, timeout: Incomplete) -> Never: ...

    def ctrl_transfer(self, dev_handle: Incomplete, bmRequestType: Incomplete, bRequest: Incomplete, wValue: Incomplete, wIndex: Incomplete, data: Incomplete, timeout: Incomplete) -> Never: ...

    def clear_halt(self, dev_handle: Incomplete, ep: Incomplete) -> Never: ...

    def reset_device(self, dev_handle: Incomplete) -> Never: ...

    def is_kernel_driver_active(self, dev_handle: Incomplete, intf: Incomplete) -> Never: ...

    def detach_kernel_driver(self, dev_handle: Incomplete, intf: Incomplete) -> Never: ...

    def attach_kernel_driver(self, dev_handle: Incomplete, intf: Incomplete) -> Never: ...
