from _typeshed import Incomplete

import usb.util as util
import copy
import operator
import usb._interop as _interop
import usb._objfinalizer as _objfinalizer
import usb._lookup as _lu
import logging
import array
import threading
import functools


class USBError(IOError):
    backend_error_code: Incomplete

    def __init__(self, strerror: Incomplete, error_code: Incomplete = None, errno: Incomplete = None) -> None: ...


class USBTimeoutError(USBError):
    ...


class NoBackendError(ValueError):
    ...


class Endpoint:
    device: Incomplete
    index: Incomplete

    def __init__(self, device: Incomplete, endpoint: Incomplete, interface: Incomplete = 0, alternate_setting: Incomplete = 0, configuration: Incomplete = 0) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def write(self, data: Incomplete, timeout: Incomplete = None) -> Incomplete: ...

    def read(self, size_or_buffer: Incomplete, timeout: Incomplete = None) -> Incomplete: ...

    def clear_halt(self) -> None: ...


class Interface:
    alternate_index: Incomplete
    configuration: Incomplete
    device: Incomplete
    index: Incomplete

    def __init__(self, device: Incomplete, interface: Incomplete = 0, alternate_setting: Incomplete = 0, configuration: Incomplete = 0) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def endpoints(self) -> tuple[Endpoint, ...]: ...

    def set_altsetting(self) -> None: ...

    def __iter__(self) -> Incomplete: ...

    def __getitem__(self, index: Incomplete) -> Endpoint: ...


class Configuration:
    device: Incomplete
    index: Incomplete

    def __init__(self, device: Incomplete, configuration: Incomplete = 0) -> None: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> str: ...

    def interfaces(self) -> tuple[Interface, ...]: ...

    def set(self) -> None: ...

    def __iter__(self) -> Incomplete: ...

    def __getitem__(self, index: Incomplete) -> Interface: ...


class Device(_objfinalizer.AutoFinalizedObject):
    def __eq__(self, other: Incomplete) -> NotImplementedType | bool: ...

    def __hash__(self) -> int: ...

    def __repr__(self) -> str: ...

    def __str__(self) -> Incomplete: ...

    def configurations(self) -> tuple[Configuration, ...]: ...

    address: int
    bus: int
    port_number: int
    speed: int

    def __init__(self, dev: Incomplete, backend: Incomplete) -> None: ...

    @property
    def langids(self) -> Incomplete: ...

    @property
    def serial_number(self) -> Incomplete: ...

    @property
    def product(self) -> Incomplete: ...

    @property
    def parent(self) -> Incomplete: ...

    @property
    def manufacturer(self) -> Incomplete: ...

    @property
    def backend(self) -> Incomplete: ...

    def set_configuration(self, configuration: Incomplete = None) -> None: ...

    def get_active_configuration(self) -> Incomplete: ...

    def set_interface_altsetting(self, interface: Incomplete = None, alternate_setting: Incomplete = None) -> None: ...

    def clear_halt(self, ep: Incomplete) -> None: ...

    def reset(self) -> None: ...

    def write(self, endpoint: Incomplete, data: Incomplete, timeout: Incomplete = None) -> Incomplete: ...

    def read(self, endpoint: Incomplete, size_or_buffer: Incomplete, timeout: Incomplete = None) -> Incomplete: ...

    def ctrl_transfer(self, bmRequestType: Incomplete, bRequest: Incomplete, wValue: Incomplete = 0, wIndex: Incomplete = 0, data_or_wLength: Incomplete = None, timeout: Incomplete = None) -> Incomplete: ...

    def is_kernel_driver_active(self, interface: Incomplete) -> Incomplete: ...

    def detach_kernel_driver(self, interface: Incomplete) -> None: ...

    def attach_kernel_driver(self, interface: Incomplete) -> None: ...

    def __iter__(self) -> Incomplete: ...

    def __getitem__(self, index: Incomplete) -> Configuration: ...

    default_timeout: property


# Refined by hand: the common find_all=False case returns one Device or None.
def find(find_all: bool = False, backend: Incomplete = None, custom_match: Incomplete = None, **args: Incomplete) -> Device | None: ...


def show_devices(verbose: Incomplete = False, **kwargs: Incomplete) -> _DescriptorInfo: ...
